import 'package:flutter/material.dart';
import 'package:gmail_clone/utils/color_const.dart';
import 'package:gmail_clone/utils/image_constant.dart';

class MailItem {
  String title, description, content, time, date, year, gmail, logourl;
  bool isRead,
      is_stared,
      is_deleted,
      is_primary,
      is_promotion,
      is_social,
      is_snoozed,
      isimportant,
      issent,
      isoutbox,
      isdraft,
      issheduled;
  Color logocolor;
  MailItem({
    required this.title,
    required this.description,
    required this.content,
    required this.time,
    required this.isRead,
    required this.gmail,
    required this.year,
    required this.date,
    this.is_stared = false,
    this.is_deleted = false,
    this.is_primary = false,
    this.is_promotion = false,
    this.is_social = false,
    this.is_snoozed = false,
    this.isimportant = false,
    this.issheduled = false,
    this.issent = false,
    this.isoutbox = false,
    this.isdraft = false,
    this.logourl = "",
    this.logocolor = Colors.transparent,
  });
}

double MySize = 0.0;
double kPadding = MySize * 0.025;

List<MailItem> mailList = [
  MailItem(
      logourl: "https://cdn2.hubspot.net/hubfs/53/image8-2.jpg",
      title: 'Google',
      description: 'This mail is from Google',
      content: 'Dummy content for the mail app!',
      time: '4:00 pm',
      isRead: false,
      gmail: 'google@gmail.com',
      year: '2024',
      date: '20 Jun',
      is_stared: true,
      is_deleted: true,
      is_promotion: false,
      is_social: true,
      is_snoozed: true,
      isimportant: false,
      issent: true),
  MailItem(
      logocolor: ColorConst.RED,
      title: 'PayPal',
      description: 'Payment received',
      content:
          'You have received a payment of 50.00. Check your PayPal account for details.',
      time: '5:00 pm',
      isRead: false,
      gmail: 'paypal@gmail.com',
      year: '2024',
      date: '27 Jun',
      is_deleted: true,
      is_promotion: false,
      is_social: true,
      is_snoozed: true,
      isimportant: false,
      isdraft: true),
  MailItem(
      logourl:
          "https://cdn1.iconfinder.com/data/icons/logotypes/32/circle-linkedin-512.png",
      title: 'LinkedIn',
      description: 'Connection request from Alice Smith',
      content:
          'Alice Smith wants to connect with you on LinkedIn. Visit their profile to accept or decline the request.',
      time: '9:45 am',
      isRead: true,
      gmail: 'linkedin@gmail.com',
      year: '2024',
      date: '23 Jun',
      is_stared: true,
      is_deleted: true,
      is_promotion: false,
      is_social: true,
      is_snoozed: true,
      isimportant: false,
      issheduled: true),
  MailItem(
      logourl: "https://logowik.com/content/uploads/images/amazon6707.jpg",
      title: 'Amazon',
      description: 'Your order has been shipped',
      content:
          'Your order #12345 has been shipped and will arrive on 25 Jun. Track your package for more details.',
      time: '1:00 pm',
      isRead: false,
      gmail: 'amazon@gmail.com',
      year: '2024',
      date: '24 Jun',
      is_stared: true,
      is_deleted: true,
      is_promotion: false,
      is_social: true,
      is_snoozed: true,
      isimportant: true,
      isdraft: true),
  MailItem(
    logocolor: Colors.yellow,
    title: 'Etsy',
    description: 'Order confirmation',
    content:
        'Your order #67890 has been confirmed. You will receive an update once it ships.',
    time: '2:00 pm',
    isRead: true,
    gmail: 'etsy@gmail.com',
    year: '2024',
    date: '28 Jun',
    is_deleted: false,
  ),
  MailItem(
    logourl:
        "https://static.vecteezy.com/system/resources/previews/020/336/373/original/netflix-logo-netflix-icon-free-free-vector.jpg",
    title: 'Netflix',
    description:
        'Spend on experiences not things. Make time for rest, relaxation and some Netflix 😉.',
    content:
        'A new episode of your favorite series is available now. Log in to watch it now.',
    time: '3:00 pm',
    isRead: true,
    gmail: 'netflix@gmail.com',
    year: '2024',
    date: '25 Jun',
    is_deleted: true,
    is_promotion: false,
    is_social: true,
    is_snoozed: true,
    isimportant: true,
  ),
  MailItem(
    logourl:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjvzC_QRv6moAhgNb5C6e3yicKgFND1g2RwA&s",
    title: 'Facebook',
    description: 'New friend request from John Doe',
    content:
        'John Doe has sent you a friend request on Facebook. Check your friend requests to respond.',
    time: '10:15 am',
    isRead: false,
    gmail: 'facebook@gmail.com',
    year: '2024',
    date: '22 Jun',
    is_deleted: false,
    is_promotion: false,
    is_social: true,
    is_snoozed: false,
    isimportant: true,
  ),
  MailItem(
    logourl:
        "https://cdn1.iconfinder.com/data/icons/logotypes/32/circle-twitter-512.png",
    title: 'Twitter',
    description: 'New follower alert',
    content:
        'You have a new follower on Twitter. Check out their profile to follow back.',
    time: '11:30 am',
    isRead: true,
    gmail: 'twitter@gmail.com',
    year: '2024',
    date: '21 Jun',
    is_deleted: false,
    is_promotion: false,
    is_social: true,
    is_snoozed: false,
    isimportant: false,
  ),
  MailItem(
    logocolor: Colors.red,
    title: 'YouTube',
    description: 'New video from your favorite channel',
    content:
        'Your favorite YouTube channel has uploaded a new video. Watch it now!',
    time: '12:00 pm',
    isRead: false,
    gmail: 'youtube@gmail.com',
    year: '2024',
    date: '20 Jun',
    is_stared: false,
    is_deleted: false,
    is_promotion: false,
    is_social: false,
    is_snoozed: false,
    isimportant: true,
  ),
  MailItem(
    logourl:
        "https://e7.pngegg.com/pngimages/793/131/png-clipart-whatsapp-instagram-social-media-logo-whatsapp-logo-social-media.png",
    title: 'Instagram',
    description: 'New like on your post',
    content:
        'Someone has liked your recent post on Instagram. Check it out now!',
    time: '1:45 pm',
    isRead: true,
    gmail: 'instagram@gmail.com',
    year: '2024',
    date: '19 Jun',
    is_deleted: false,
    is_promotion: false,
    is_social: true,
    is_snoozed: true,
    isimportant: false,
  ),
  MailItem(
    logourl:
        "https://1000logos.net/wp-content/uploads/2017/08/Snapchat-logo.jpg",
    title: 'Snapchat',
    description: 'New snap from Emily',
    content:
        'Emily has sent you a new snap on Snapchat. Open the app to view it.',
    time: '2:30 pm',
    isRead: true,
    gmail: 'snapchat@gmail.com',
    year: '2024',
    date: '18 Jun',
    is_stared: false,
    is_deleted: false,
    is_promotion: false,
    is_social: true,
    is_snoozed: false,
    isimportant: false,
  ),
  MailItem(
    logocolor: Colors.green,
    title: 'WhatsApp',
    description: 'New message from Group Chat',
    content:
        'You have a new message in your Group Chat on WhatsApp. Check it now!',
    time: '3:15 pm',
    isRead: false,
    gmail: 'whatsapp@gmail.com',
    year: '2024',
    date: '17 Jun',
    is_stared: true,
    is_deleted: false,
    is_promotion: false,
    is_social: false,
    is_snoozed: false,
    isimportant: true,
  ),
  MailItem(
    logourl:
        "https://cdn1.iconfinder.com/data/icons/logotypes/32/circle-tumblr-512.png",
    title: 'Tumblr',
    description: 'New post from followed blog',
    content: 'A blog you follow on Tumblr has made a new post. Read it now!',
    time: '4:00 pm',
    isRead: true,
    gmail: 'tumblr@gmail.com',
    year: '2024',
    date: '16 Jun',
    is_deleted: false,
    is_promotion: false,
    is_social: true,
    is_snoozed: true,
    isimportant: false,
  ),
  MailItem(
    logocolor: Colors.purple,
    title: 'Reddit',
    description: 'New comment on your post',
    content:
        'You have a new comment on your Reddit post. Check the thread for more details.',
    time: '5:45 pm',
    isRead: false,
    gmail: 'reddit@gmail.com',
    year: '2024',
    date: '15 Jun',
    is_stared: true,
    is_deleted: false,
    is_promotion: false,
    is_social: true,
    is_snoozed: false,
    isimportant: true,
  ),
  MailItem(
    logourl:
        "https://www.shutterstock.com/image-vector/pinterest-icon-logo-art-design-260nw-2271009451.jpg",
    title: 'Pinterest',
    description: 'New pin from followed board',
    content:
        'A new pin has been added to a board you follow on Pinterest. Check it out!',
    time: '6:30 pm',
    isRead: true,
    gmail: 'pinterest@gmail.com',
    year: '2024',
    date: '14 Jun',
    is_stared: false,
    is_promotion: true,
  ),
  MailItem(
    logocolor: Colors.yellow,
    title: 'VK',
    description: 'New message from Maria',
    content: 'Maria has sent you a new message on VK. Open the app to read it.',
    time: '7:15 pm',
    isRead: false,
    gmail: 'vk@gmail.com',
    year: '2024',
    date: '13 Jun',
    is_stared: false,
    is_deleted: false,
    is_social: true,
    is_snoozed: true,
  ),
  MailItem(
    logocolor: Colors.blue,
    title: 'TikTok',
    description: 'New video recommendation',
    content: 'You have a new video recommendation on TikTok. Check it out now!',
    time: '8:00 pm',
    isRead: true,
    gmail: 'tiktok@gmail.com',
    year: '2024',
    date: '12 Jun',
    is_stared: false,
    isimportant: true,
  ),
  MailItem(
    logocolor: Colors.green,
    title: 'Line',
    description: 'New message from Alex',
    content:
        'Alex has sent you a new message on Line. Open the app to view it.',
    time: '8:45 pm',
    isRead: false,
    gmail: 'line@gmail.com',
    year: '2024',
    date: '11 Jun',
    is_stared: true,
    isimportant: true,
  ),
  MailItem(
    logocolor: ColorConst.BLUE,
    title: 'Spotify',
    description: 'Weekly playlist update',
    content:
        'Check out your weekly playlist update with new songs and recommendations.',
    time: '10:00 am',
    isRead: false,
    gmail: 'spotify@gmail.com',
    year: '2024',
    date: '26 Jun',
    is_stared: true,
    is_deleted: true,
    is_promotion: true,
    is_social: true,
    is_snoozed: true,
    isimportant: true,
  ),
  MailItem(
      logourl:
          "https://assets.turbologo.com/blog/en/2019/07/19085130/twitter-bird-logo.png",
      title: 'Twitter',
      description: 'Follow request from John Doe',
      content:
          'John Doe has sent you a follow request. Check out their profile and accept or decline the request.',
      time: '8:30 pm',
      isRead: false,
      gmail: 'twitter@gmail.com',
      year: '2024',
      date: '22 Jun',
      is_social: true),
  MailItem(
    logocolor: Colors.green,
    title: 'Slack',
    description: 'New message from team',
    content:
        'You have a new message from your team on Slack. Check the app for more details.',
    time: '6:00 pm',
    isRead: false,
    gmail: 'slack@gmail.com',
    year: '2024',
    date: '29 Jun',
    is_stared: true,
    is_deleted: true,
    is_social: true,
    is_snoozed: true,
  ),
  MailItem(
      logourl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjvzC_QRv6moAhgNb5C6e3yicKgFND1g2RwA&s",
      title: 'Facebook',
      description: 'New login from an unknown device',
      content:
          'Your Facebook account was accessed from a new device. If this wasn’t you, please secure your account.',
      time: '11:15 am',
      isRead: true,
      gmail: 'facebook@gmail.com',
      year: '2024',
      date: '21 Jun',
      is_stared: true,
      is_social: true),
  MailItem(
    logocolor: Colors.purple,
    title: 'Dropbox',
    description: 'Shared folder access',
    content:
        'You have been given access to a new shared folder. Click here to view the contents.',
    time: '7:00 pm',
    isRead: true,
    gmail: 'dropbox@gmail.com',
    year: '2024',
    date: '30 Jun',
    is_stared: true,
    is_deleted: true,
    is_social: true,
    is_snoozed: true,
  ),
  MailItem(
    logocolor: Colors.tealAccent,
    title: 'GitHub',
    description: 'Repository update',
    content:
        'A new commit has been pushed to your repository. Visit GitHub to review the changes.',
    time: '12:00 pm',
    isRead: false,
    gmail: 'github@gmail.com',
    year: '2024',
    date: '01 Jul',
    is_stared: true,
  ),
];

final List<String> menuTabItems = [
  "Move to",
  "Snooze",
  "Mark as important",
  "Mute",
  "Print",
  "Report spam",
  "Help and feedback"
];
final List<String> menuMailItems = [
  "Reply all",
  "Forward",
  "Add star",
  "Print",
  "Mark unread from here",
  "Block GitHub",
];
List drawerItems = [
  {'icon': Icons.all_inbox, 'title': 'All Inbox'},
  {'icon': Icons.inbox, 'title': 'Primary'},
  {'icon': Icons.group, 'title': 'Social'},
  {'icon': Icons.sell_outlined, 'title': 'Promotion'},
  {'icon': Icons.star_rate_outlined, 'title': 'Starred'},
  {'icon': Icons.snooze_outlined, 'title': 'Snoozed'},
  {'icon': Icons.label_important_outline, 'title': 'Important'},
  {'icon': Icons.send_outlined, 'title': 'Sent'},
  {'icon': Icons.send_and_archive_outlined, 'title': 'Scheduled'},
  {'icon': Icons.outbox_outlined, 'title': 'Outbox'},
  {'icon': Icons.drafts_outlined, 'title': 'Drafts'},
  {'icon': Icons.all_inbox, 'title': 'All mails'},
  {'icon': Icons.block, 'title': 'Spam'},
  {'icon': Icons.delete_outline_outlined, 'title': 'Bin'},
  {'icon': Icons.calendar_today, 'title': 'Calendar'},
  {'icon': Icons.account_circle_outlined, 'title': 'Contact'},
  {'icon': Icons.settings, 'title': 'Settings'},
  {'icon': Icons.help_outline, 'title': 'Help and feedback'},
];

class AccountsItem {
  String name, mail, imgPath;
  bool ismainprofile, isicon;
  int notificationcount;
  IconData? profileicon;
  AccountsItem({
    required this.name,
    required this.mail,
    required this.imgPath,
    this.ismainprofile = false,
    this.notificationcount = 0,
    this.isicon = false,
    this.profileicon,
  });
}

List<AccountsItem> accountlist = [
  AccountsItem(
      imgPath: ImagePath.PROFILE2,
      mail: 'snehamol223@gmail.com',
      ismainprofile: true,
      isicon: true,
      profileicon: Icons.camera_alt,
      name: 'Sneha Raj',
      notificationcount: 3),
  AccountsItem(
      imgPath: ImagePath.PROFILE3,
      mail: 'shann3@gmail.com',
      name: 'Shann Rai',
      notificationcount: 7),
  AccountsItem(
      imgPath: ImagePath.PROFILE1,
      mail: 'surajravi@gmail.com',
      name: 'Suraj Ravi',
      notificationcount: 8),
];
